### ISSUE TITLE
[Bug] Ambigous columns

### ISSUE THREAD

**Issue by nszoni** [fivetran/dbt_shopify_source#55]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

`properties` and `status` columns called twice in the CTE resulting in ambiguity

- `models/stg_shopify__order_line.sql`
- `models/stg_shopify__product.sql`

### Relevant error log or model output

```shell
13:14:18  Database Error in model stg_shopify__order_line (models/stg_shopify__order_line.sql)
13:14:18    Column name properties is ambiguous at [484:9]
13:14:18    compiled Code at target/run/shopify_source/models/stg_shopify__order_line.sql
13:14:18  
13:14:18  Database Error in model stg_shopify__product (models/stg_shopify__product.sql)
13:14:18    Column name status is ambiguous at [158:9]
13:14:18    compiled Code at target/run/shopify_source/models/stg_shopify__product.sql
```

### Expected behavior

Columns are called once eliminating the chance of ambiguity.

### dbt Project configurations

```
require-dbt-version: [">=1.4.0", "<2.0.0"]
```

### Package versions

```yml
packages:
  - package: dbt-labs/dbt_utils
    version: [">=1.0.0", "<1.1.0"]
  - package: dbt-labs/codegen
    version: [">=0.9.0", "<1.0.0"]
  - package: fivetran/shopify
    version: [">=0.8.0", "<0.9.0"]
  - package: fivetran/google_ads
    version: [">=0.9.0", "<0.10.0"]
  - package: fivetran/google_ads_source
    version: [">=0.9.0", "<0.10.0"]
  - package: fivetran/microsoft_ads
    version: [">=0.6.0", "<0.7.0"]
  - package: fivetran/facebook_ads
    version: [">=0.6.0", "<0.7.0"]
  - package: fivetran/ad_reporting
    version: [">=1.2.0", "<1.3.0"]
  - package: calogica/dbt_expectations
    version: [">=0.8.0", "<0.9.0"]
# - package: fivetran/klaviyo
#   version: [">=0.5.0", "<0.6.0"]
  - package: dbt-labs/segment
    version: [">=0.9.0", "<1.0.0"]
  - package: fivetran/instagram_business
    version: [">=0.2.0", "<0.3.0"]
  - package: fivetran/fivetran_utils
    version: [">=0.4.0", "<0.5.0"]
  - package: dbt-labs/metrics
    version: [">=1.4.0", "<1.5.0"]
```

### What database are you using dbt with?

bigquery

### dbt Version

```
Core:
  - installed: 1.4.0
  - latest:    1.4.1 - Update available!

  Your version of dbt-core is out of date!
  You can find instructions for upgrading here:
  https://docs.getdbt.com/docs/installation

Plugins:
  - bigquery: 1.4.0 - Up to date!
```

### Are you willing to open a PR to help address this issue?

- [X] Yes.
- [ ] Yes, but I will need assistance and will schedule time during our [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance
- [ ] No.
