### ISSUE TITLE
Multiple Shopify Shops

### ISSUE THREAD

**Issue by elvisace** [fivetran/dbt_shopify_source#6]
In our setup, we have multiple shopify shops (they all land in different schemas in snowflake) and would like to use this package on all of them. Is there any way to achieve this? Or maybe point me in the right direction and I'd be more than glad to generate a PR?

Thanks for the package guys!

**Comment by fivetran-kristin** [comment]
Hey @elvisace -- great question! The way we have designed the package to accommodate multiple connectors is as follows:

- In snowflake/your dbt project, union all of your various shopify data sources into one single source.  For example, 
```
select * from shopify_one.customer
union all
select * from shopify_two.customer
```

- Then, in your `dbt_project.yml` file, overwrite the source definitions using the following variables:
```
vars:
  shopify_source:
    customer_source: shopify.unioned_customer (or whatever you named it)
    order_line_refund_source: shopify.unioned_order_line_refund (or whatever you named it)
    order_line_source: shopify.unioned_order_line (or whatever you named it)
    order_source: shopify.unioned_order (or whatever you named it)
    product_source: shopify.unioned_product (or whatever you named it)
```

The final result will be a set of transformed tables, which will combine all of your shopify shops data together.

Let us know how you feel about this approach.  Also, we have office hours if you want to discuss live -- book [here](5tran.co/office-hours).
