### ISSUE TITLE
[Bug] Transactions staging table fails on invalid identifier

### ISSUE THREAD

**Issue by mjrsnyder** [fivetran/dbt_shopify_source#76]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

When running `dbt run` I receive the error attached below.

The stg_shopify__transaction.sql model is referencing the `authorization` column by `authorization_code` which does not match my environment or the ERD supplied by Fivetran.

### Relevant error log or model output

```shell
[info ] [MainThread]: Completed with 1 error and 0 warnings: 
[info ] [MainThread]:  
[error] [MainThread]: Database Error in model stg_shopify__transaction (models/stg_shopify__transaction.sql) 
[error] [MainThread]:   000904 (42000): SQL compilation error: error line 372 at position 18
[error] [MainThread]:   invalid identifier 'AUTHORIZATION'
[error] [MainThread]:   compiled Code at target/run/shopify_source/models/stg_shopify__transaction.sql
```

### Expected behavior

I expect the authorization column to either be renamed to `authorization_code` or persist as `authorization` without an error being thrown

### dbt Project configurations

```
    shopify_database: 'raw' 
    shopify_union_schemas: ['shopify_1', 'shopify_2', 'shopify_3']
    shopify_source:
      transaction_pass_through_columns:
        - name: "authorization"
      product_variant_pass_through_columns:
        - name: "requires_shipping"
      order_pass_through_columns:
        - name: reference
        - name: source_identifier
```

### Package versions

  - package: dbt-labs/metrics
    version: 1.3.2
  - package: fivetran/shopify
    version: 0.9.0
  - package: fivetran/asana
    version: 0.7.0
  - package: fivetran/github
    version: 0.7.0
  - package: fivetran/hubspot
    version: 0.12.0

### What database are you using dbt with?

snowflake

### dbt Version

1.3.1

### Are you willing to open a PR to help address this issue?

- [X] Yes.
- [ ] Yes, but I will need assistance and will schedule time during our [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance
- [ ] No.
